server:
  port: 8083
spring:
  application:
    name: RPS_GAME
  config:
    import: configserver:http://localhost:8081
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
resilience4j:
  circuitbreaker:
    instance:
      external:
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED